name:                LambdaGen
version:             0.1.0.0
github:              "leanil/LambdaGen"
license:             BSD3
author:              "András Leitereg"
maintainer:          "leanil94@gmail.com"
copyright:           "2018 András Leitereg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/leanil/LambdaGen#readme>

dependencies:
- aeson
- base >= 4.7
- comonad
- containers
- deriving-compat
- directory
- either
- free
- mtl
- neat-interpolation
- process
- random
- recursion-schemes
- text
- unordered-containers
- vector
- vinyl
- websockets

library:
  source-dirs: src

executables:
  LambdaGen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambdaGen

tests:
  LambdaGen-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LambdaGen
